sudo: required
services:
  - docker
before_install:
  - docker build -t phonekham/docker-react -f Dockerfile.dev .
script:
  - docker run phonekham/docker-react npm run test -- --coverage
  - "travis_wait 30 sleep 1800 &"
  - curl -s https://raw.githubusercontent.com/xeon-zolt/arch-travis/master/arch-travis.sh | bash
deploy:
  provider: elasticbeanstalk
  region: "ap-southeast-1"
  app: "docker-react"
  env: "DockerReact-env"
  bucket_name: "elasticbeanstalk-ap-southeast-1-528502753315"
  bucket_path: "docker-react"
  on:
    branch_master: master
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key:
    secure: "$AWS_SECRET_KEY"
